### ISSUE TITLE
Testing To Do

### ISSUE THREAD

**Issue by droglenc** [droglenc/FSA#23]
I recently updated the structure for testing and found the following testing needs:

- [x] `capHistConvert()` ... More tests that conversions do what they are supposed to. Was Issue #1 .
- [x] expandCounts_OUT
- [x] expandLenFreqs_OUT
- [x] metaM_OUT
- [x] mrClosed_OUT
- [x] mrClosed_XXX ... force some different types of CIs to be computed.
- [x] capHist_OUT
- [x] `capHistConvert()` ... More tests of warnings and errors. Was Issue #1 .
- [x] `capHistConvert()` ... Make tests for `cols2use=` and `cols2ignore=` here. Was Issue #1 .
- [x] ciDists_VALIDATE
- [x] ciDists_OUT ... `hyperCI()` and `poiCI()`
- [x] ciDists_VALIDATE ... `hyperCI()` and `poiCI()`
- [x] dunnTest_OUT
- [x] ksTest_OUT
- [x] sumTable_VALIDATE
